### ISSUE TITLE
Compatible con Laravel 5.3

### ISSUE THREAD

**Issue by cristianmeza** [malahierba-lab/chile-rut#2]
Estimados, les quería pedir si podrían hacer este package compatible con Laravel 5.3, ya que al intentar instalarlo da error.
Gracias por el package, me ha ayudado mucho. Saludos.

**Comment by fsobarzo** [comment]
que error te tira ?, lo solucionaste ? :O?

**Comment by cristiansantana** [comment]
Ya está disponible para Laravel 5.3
