### ISSUE TITLE
Incompatibilidad Laravel 5.4

### ISSUE THREAD

**Issue by SebastianBar** [malahierba-lab/chile-rut#3]
En el archivo ChileRutServiceProvider, hay que reemplazar

$this->app['chilerut'] = $this->app->share(function($app

por

$this->app->singleton('chilerut', function($app

El método share lo eliminaron en la última revisión (estaba deprecado hace años) y se debe utilizar singleton. Haciendo ese cambio, funciona sin problemas.

**Comment by cristiansantana** [comment]
Listo el cambio sugerido, muchas gracias por el feedback.
