### ISSUE TITLE
Error al intentar desinstalar chile-rut

### ISSUE THREAD

**Issue by Pablo-Araya** [malahierba-lab/chile-rut#4]
He intentado una y otra vez desinstalar el paquete chile-rut, sin embargo no he podido lograrlo sin que me aparezca un error y me bote mi proyecto

 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Malahierba\ChileRut\ChileRutServiceProvider' not found

```
composer remove malahierba-lab/chile-rut
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)

Package operations: 0 installs, 0 updates, 1 removal
  - Removing malahierba-lab/chile-rut (5.1.3)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
```
### In ProviderRepository.php line 208:

  Class 'Malahierba\ChileRut\ChileRutServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Removal failed, reverting ./composer.json to its original content.

Alguien sabe como puedo solucionarlo ?
Saludos.

**Comment by Pablo-Araya** [comment]
Tuve que instalar todo el repositorio nuevamente.
Saludos

**Comment by dazjavier** [comment]
Para la próxima podrías intentar con un `composer dump-autoload`, en lugar de clonar nuevamente el repositorio.

**Comment by Pablo-Araya** [comment]
@dazjavier ..... ya lo había intentado, incluso forzándolo con optimize " -o"

**Comment by dazjavier** [comment]
Entiendo. Errores misteriosos que quién sabe cómo se producen, ni cómo se podrían evitar jaja.
Me alegro que se haya solucionado.
Saludos ✌️

**Comment by Pablo-Araya** [comment]
gracias de todos modos !!!
saludos

**Comment by cristiansantana** [comment]
@Pablo-Araya disculpa por no responder antes, estuve mirando lo que indicas y mi suposición es que se te ha quedado "algo" en uso del paquete antes de removerlo.

En el archivo **config/app.php** elimina de `'providers'` la linea:

`Malahierba\ChileRut\ChileRutServiceProvider::class`

Elimina también el alias (si es que lo creaste) en la sección "aliases" del mismo archivo. Luego desinstala como lo has hecho hasta ahora.

**Comment by Pablo-Araya** [comment]
Efectivamente hice eso apenas vi el error... pero no funcionó.
De todas formas, ya solucioné el problema clonando el repositorio a uno nuevo y eliminando manualmente el composer.json
