### ISSUE TITLE
Upgrade Laravel 6

### ISSUE THREAD

**Issue by Gemius01** [malahierba-lab/chile-rut#8]
Hello, chile-rut requires only 5.x laravel framework versions. I need to upgrade my project with laravel 6 but this library isn't be able work with this versión.

malahierba-lab/chile-rut 5.1.0 requires laravel/framework 5.1.* -> satisfiable by laravel/framework[5.1.x-dev].

**Comment by cristiansantana** [comment]
Done. Thank for your alert about this

**Comment by Gemius01** [comment]
@cristiansantana A doubt, was the package updated in packagist and composer? still giving me incompatibility issues, thanks for your support

**Comment by cristiansantana** [comment]
@Gemius01 you right. My mistake. I don't setup new packagist web hook for this proyect. Now is resolved.
